### ISSUE TITLE
add `Alert` component

### ISSUE THREAD

**Issue by radnan** [optimizely-axiom/optiaxiom#121]

**Comment by mostafa-K-raihan** [comment]
Is this similar to the CMP Alert component? I did not find any Alert component similar to CMP in Radix UI, the closest I got was the Toast component, but there is a difference between these two.

**Comment by ImperishableMe** [comment]
@radnan bhaia, We will need this for our Opal frontend work. I want to work on this. Would you be able to assign this issue to me? Also, do you have any plan/reference of the exposed API for this component?

**Comment by radnan** [comment]
this is similar to SectionMessage in CMP - and we will have a separate Toast component

@ImperishableMe feel free to start please - should have similar semantics to CMP SectionMessage
