### ISSUE TITLE
Feedback for “Table”

### ISSUE THREAD

**Issue by Ben-Holme** [optimizely-axiom/optiaxiom#655]
The example in the docs mentions a "TableHeader" component. But it's called "TableHead".

**Comment by Ben-Holme** [comment]
I have to manually add @tanstack/react-table

**Comment by radnan** [comment]
> The example in the docs mentions a "TableHeader" component. But it's called "TableHead".

we've actually renamed the component to `TableHeader` to keep the `Header/Body/Footer` naming consistent across components

**Comment by radnan** [comment]
> I have to manually add @tanstack/react-table

this is expected since `@tanstack/react-table` is a peer dependency (similar to `react`). we'll make sure to mention this when writing up the docs for `DataTable`.
