### ISSUE TITLE
(ProgressBar) style issues

### ISSUE THREAD

**Issue by MunifTanjim** [optimizely-axiom/optiaxiom#68]
- Width is fixed at `50%`
- No way to override the width easily
- Border radius looks odd, the outer part is squared but inner part is rounded.
    <img width="67" alt="image" src="https://github.com/optimizely-axiom/optiaxiom/assets/8050659/086a5502-17c2-414d-a05e-094fe9db2e2c">

**Comment by MunifTanjim** [comment]
@ImperishableMe Somehow I can't add you to this issue as assignee.

cc: @radnan

**Comment by ImperishableMe** [comment]
Issued https://github.com/optimizely-axiom/optiaxiom/pull/71, but cannot assign you as a reviewer @MunifTanjim bhai.

**Comment by radnan** [comment]
> @ImperishableMe Somehow I can't add you to this issue as assignee.
> 
> cc: @radnan

this is an odd and annoying thing about GH - seems until the user interacts with the issue you can't assign them - not sure how we get around that

**Comment by ImperishableMe** [comment]
> Border radius looks odd, the outer part is squared but inner part is rounded.

@MunifTanjim  bhai, in the [Opal design](https://www.figma.com/design/GH25lYLDM34molSm1yhQO3/Opal-Guidelines?m=dev&node-id=1303-37000), we have `border-radius` only for the inner box. Of all the allowed `rounded` values in the `Box` component, `lg` seemed to come close to the design. Should I remove `border-radius` altogether?
 
<img width="545" alt="image" src="https://github.com/optimizely-axiom/optiaxiom/assets/27671454/b4065bab-70af-4305-9fe3-5bd8c2989a8e">

**Comment by MunifTanjim** [comment]
@ImperishableMe this is what I got from Figma:

<img width="377" alt="image" src="https://github.com/optimizely-axiom/optiaxiom/assets/8050659/e2011989-47a9-49e9-b68f-20605d1d6047">

<img width="173" alt="image" src="https://github.com/optimizely-axiom/optiaxiom/assets/8050659/d4d31d21-709e-4d54-a52a-afcb8fa8d1e7">

The whole thing is rounded.

**Comment by ImperishableMe** [comment]
@MunifTanjim bhaia, https://github.com/optimizely-axiom/optiaxiom/pull/71 is merged now, please let me know if that solves all the concern of this issue.

**Comment by MunifTanjim** [comment]
Yes. looks good.
